package mdn.jh.automation.devices.mqtt;

import java.nio.charset.StandardCharsets;import java.util.HashSet;import java.util.Properties;import java.util.Set;import org.eclipse.paho.client.mqttv3.*;import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;import org.w3c.dom.*;
import io.moquette.broker.Server;import mdn.jh.automation.device.*;import mdn.jh.automation.gui.*;import mdn.jh.automation.io.source.DataSource;

/** Single built-in MQTT 3.1.1 broker and its local publisher/subscriber client. */
public class MqttBrokerDevice extends Device{
 private int port=1883;private boolean autostart;private transient Server broker;private transient MqttClient client;private transient Set<String> subscriptions=new HashSet<>();private transient String error="";
 public MqttBrokerDevice(){super(TYPE_MQTT_BROKER);initialize();}private void initialize(){if(dataSourceHandler==null)dataSourceHandler=new MqttDataSourceHandler(this);if(dataSinkHandler==null)dataSinkHandler=new MqttDataSinkHandler(this);if(subscriptions==null)subscriptions=new HashSet<>();}
 public synchronized int getPort(){return port;}public synchronized boolean isAutostart(){return autostart;}public synchronized boolean isBrokerRunning(){return broker!=null;}public synchronized String getBrokerError(){return error;}
 public synchronized void configure(int p,boolean a){if(p<1||p>65535)throw new IllegalArgumentException("Port must be between 1 and 65535");if(isBrokerRunning()&&port!=p)throw new IllegalStateException("Stop the MQTT broker before changing its port");port=p;autostart=a;}
 public synchronized void startBroker()throws Exception{if(broker!=null)return;Properties props=new Properties();props.setProperty("port",Integer.toString(port));props.setProperty("host","0.0.0.0");props.setProperty("allow_anonymous","true");props.setProperty("persistence_enabled","false");Server created=new Server();try{created.startServer(props);broker=created;error="";ensureClient();}catch(Exception e){try{created.stopServer();}catch(Exception ignored){}error=e.getMessage();throw e;}}
 public synchronized void stopBroker(){disconnectClient();if(broker!=null)broker.stopServer();broker=null;subscriptions.clear();}
 private synchronized void ensureClient()throws MqttException{if(broker==null)return;if(client!=null&&client.isConnected())return;disconnectClient();client=new MqttClient("tcp://127.0.0.1:"+port,"home-automation-"+getDeviceID(),new MemoryPersistence());client.setCallback(new MqttCallback(){public void connectionLost(Throwable cause){subscriptions.clear();}public void deliveryComplete(IMqttDeliveryToken token){}public void messageArrived(String topic,MqttMessage message){for(DataSource source:getDataSourceHandler().getMyDataSources())if(source instanceof MqttDataSource&&MqttTopic.isMatched(((MqttDataSource)source).getTopic(),topic))((MqttDataSource)source).receive(message.getPayload());}});MqttConnectOptions options=new MqttConnectOptions();options.setAutomaticReconnect(true);options.setCleanSession(true);client.connect(options);subscriptions.clear();}
 private synchronized void disconnectClient(){if(client!=null)try{if(client.isConnected())client.disconnect();client.close();}catch(Exception ignored){}client=null;}
 public synchronized void refreshSubscriptions(){try{ensureClient();if(client==null||!client.isConnected())return;for(DataSource source:getDataSourceHandler().getMyDataSources())if(source instanceof MqttDataSource){MqttDataSource mqtt=(MqttDataSource)source;if(subscriptions.add(mqtt.getTopic()))client.subscribe(mqtt.getTopic(),mqtt.getQos());}}catch(Exception e){error=e.getMessage();for(DataSource source:getDataSourceHandler().getMyDataSources())if(source instanceof MqttDataSource)((MqttDataSource)source).invalidate();}}
 public synchronized void publish(String topic,String payload,int qos,boolean retained)throws Exception{ensureClient();if(client==null||!client.isConnected())throw new IllegalStateException("MQTT broker is stopped");MqttMessage message=new MqttMessage(payload.getBytes(StandardCharsets.UTF_8));message.setQos(qos);message.setRetained(retained);client.publish(topic,message);}
 @Override public void startUpdateThreads(){super.startUpdateThreads();if(autostart)try{startBroker();}catch(Exception e){error=e.getMessage();}}@Override public void stopUpdateThreads(){stopBroker();super.stopUpdateThreads();}
 @Override public DataSourceHandler getDataSourceHandler(){initialize();return dataSourceHandler;}@Override public DataSinkHandler getDataSinkHandler(){initialize();return dataSinkHandler;}@Override public DataSourceCreator getDataSourceCreator(){return null;}@Override public DataSinkCreator getDataSinkCreator(){return null;}@Override public String getName(){return"Built-in MQTT Broker";}
 @Override protected Node getSpecificStorage(Document d){Element root=d.createElement("MqttBroker");root.setAttribute("port",Integer.toString(port));root.setAttribute("autostart",Boolean.toString(autostart));return root;}@Override public boolean initSpecific(Node n)throws Exception{NodeList l=n.getChildNodes();for(int i=0;i<l.getLength();i++)if("MqttBroker".equals(l.item(i).getNodeName())){Node c=l.item(i);configure(Integer.parseInt(c.getAttributes().getNamedItem("port").getNodeValue()),Boolean.parseBoolean(c.getAttributes().getNamedItem("autostart").getNodeValue()));NodeList nested=c.getChildNodes();for(int j=0;j<nested.getLength();j++){if("DataSources".equals(nested.item(j).getNodeName()))dataSourceHandler=new MqttDataSourceHandler(this,nested.item(j));if("DataSinks".equals(nested.item(j).getNodeName()))dataSinkHandler=new MqttDataSinkHandler(this,nested.item(j));}}initialize();return true;}
}
