let socket,valueTimer,layout={pages:[]},catalog=[],values=new Map(),activePageId=null,editingItemId=null;
let authState={enabled:false,initialized:true,authenticated:false,canView:true,canWrite:true,anonymousView:false};

function connect(){if(socket&&(socket.readyState===WebSocket.OPEN||socket.readyState===WebSocket.CONNECTING))return;setConnection('Verbindung wird aufgebaut…',false);const protocol=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(protocol+'://'+location.host+'/automation');socket.onopen=()=>{setConnection('Verbunden',true);send('authStatus')};socket.onmessage=event=>{try{handleMessage(JSON.parse(event.data))}catch(error){toast('Ungültige Serverantwort: '+error.message,true)}};socket.onerror=()=>setConnection('Verbindungsfehler',false);socket.onclose=()=>{setConnection('Getrennt',false);clearInterval(valueTimer)}}
function send(message){if(!socket||socket.readyState!==WebSocket.OPEN){connect();return false}socket.send(message);return true}
function setConnection(text,active){const element=document.querySelector('#connection-state');element.textContent=text;element.classList.toggle('active',active)}
function handleMessage(message){if(message.auth)applyAuth(message.auth);if(message.authError){toast(message.authError,true);if(message.loginRequired)openAuthDialog();return}if(message.error){toast(message.error,true);return}if(message.dashboard){layout=message.layout||layout;catalog=message.catalog||catalog;setValues(message.values);ensureActivePage();render();startValueUpdates()}else if(message.auth&&message.auth.canView)send('dashboardGet');if(message.dashboardValues){setValues(message.dashboardValues);renderValues()}if(message.componentUpdates){message.componentUpdates.forEach(component=>values.set(Number(component.id),{id:component.id,value:component.value,valid:component.valid}));renderValues()}}
function applyAuth(state){authState=state;const status=document.querySelector('#auth-state'),button=document.querySelector('#auth-button');status.textContent=!state.enabled?'Benutzerverwaltung aus':state.authenticated?state.username+(state.canWrite?' · Schreiben':' · Lesen'):state.anonymousView?'Anonyme Ansicht':'Anmeldung erforderlich';button.hidden=!state.enabled;button.textContent=state.authenticated?'Abmelden':'Anmelden';button.onclick=state.authenticated?logout:openAuthDialog;document.querySelector('#editor-toolbar').hidden=!state.canWrite;document.body.classList.toggle('editing',state.canWrite);if(state.authenticated&&document.querySelector('#auth-dialog').open)document.querySelector('#auth-dialog').close();if(!state.canView)openAuthDialog()}
function startValueUpdates(){clearInterval(valueTimer);valueTimer=setInterval(()=>send('dashboardValues'),1000)}
function setValues(items){values=new Map((items||[]).map(item=>[Number(item.id),item]))}
function ensureActivePage(){if(!layout.pages?.length)return;if(!layout.pages.some(page=>page.id===activePageId))activePageId=layout.pages[0].id}
function activePage(){return layout.pages.find(page=>page.id===activePageId)}
function render(){renderTabs();renderCanvas()}
function renderTabs(){const tabs=document.querySelector('#dashboard-tabs');tabs.replaceChildren();(layout.pages||[]).forEach(page=>{const button=document.createElement('button');button.textContent=page.name;button.classList.toggle('active',page.id===activePageId);button.onclick=()=>{activePageId=page.id;render()};tabs.append(button)})}
function renderCanvas(){const canvas=document.querySelector('#dashboard-canvas'),page=activePage();canvas.replaceChildren();if(!page){const empty=document.createElement('p');empty.className='empty-dashboard';empty.textContent='Noch keine Dashboard-Seite vorhanden.';canvas.append(empty);return}(page.items||[]).forEach(item=>canvas.append(createItem(item)))}
function createItem(item){const element=document.createElement('article');element.className='dashboard-item '+item.type;element.dataset.id=item.id;element.style.left=item.x+'px';element.style.top=item.y+'px';element.style.width=item.width+'px';element.style.height=(item.height||70)+'px';if(item.type==='label')element.append(document.createTextNode(item.text));else if(item.type==='value'){const output=document.createElement('span');output.className='dashboard-value';element.append(output);updateValueElement(element,item)}else createControlContent(element,item);if(authState.canWrite){const actions=document.createElement('span'),edit=document.createElement('button'),remove=document.createElement('button'),longPress=item.type==='pushbutton'||item.type==='switch';actions.className='item-actions';edit.textContent='✎';edit.title=longPress?'Zum Bearbeiten 1 Sekunde gedrückt halten':'Bearbeiten';remove.textContent='×';remove.title=longPress?'Zum Löschen 1 Sekunde gedrückt halten':'Löschen';remove.className='delete';if(longPress){bindLongPress(edit,()=>editItem(item));bindLongPress(remove,()=>removeItem(item.id))}else{edit.onclick=event=>{event.stopPropagation();editItem(item)};remove.onclick=event=>{event.stopPropagation();removeItem(item.id)}}actions.append(edit,remove);element.append(actions);makeDraggable(element,item)}return element}
function bindLongPress(button,action){let timer,activated=false;const cancel=()=>{clearTimeout(timer);timer=null;button.classList.remove('holding')};button.addEventListener('pointerdown',event=>{event.stopPropagation();event.preventDefault();activated=false;button.setPointerCapture(event.pointerId);button.classList.add('holding');timer=setTimeout(()=>{activated=true;cancel();action()},1000)});button.addEventListener('pointerup',event=>{event.stopPropagation();cancel()});button.addEventListener('pointercancel',cancel);button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();if(!activated)cancel()})}
function createControlContent(element,item){element.classList.add('control');const button=document.createElement('button'),state=document.createElement('small');if(item.type==='pushbutton'&&item.name){const name=document.createElement('span');name.className='control-name';name.textContent=item.name;element.append(name)}button.type='button';button.className='dashboard-control';button.textContent=item.type==='pushbutton'?'Push':'Switch';button.disabled=!authState.canWrite;state.className='control-value';element.append(button,state);if(item.type==='pushbutton'){button.addEventListener('pointerdown',event=>{event.stopPropagation();button.setPointerCapture(event.pointerId);operateControl(item,'set',true)});const release=event=>{event.stopPropagation();operateControl(item,'set',false)};button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release)}else button.addEventListener('click',event=>{event.stopPropagation();operateControl(item,'toggle')});updateControlElement(element,item)}
function operateControl(item,action,value){if(!authState.canWrite)return;const request={id:Number(item.componentId),action};if(value!==undefined)request.value=value;send('webSource:'+JSON.stringify(request))}
function updateValueElement(element,item){const data=values.get(Number(item.componentId)),output=element.querySelector('.dashboard-value');if(!output)return;element.classList.toggle('invalid',!data||!data.valid);if(!data){output.textContent='Nicht verfügbar';return}let display=data.value;const numeric=Number(data.value);if(Number.isFinite(numeric)){const scaled=numeric*Number(item.scale??1);display=Number.isInteger(scaled)?String(scaled):String(Number(scaled.toPrecision(12)))}const unit=item.unit||'';output.textContent=item.unitPlacement==='prefix'?(unit?unit+' ':'')+display:display+(unit?' '+unit:'')}
function updateControlElement(element,item){const data=values.get(Number(item.componentId)),button=element.querySelector('.dashboard-control'),state=element.querySelector('.control-value'),active=String(data?.value)==='true';element.classList.toggle('invalid',!data||!data.valid);button?.classList.toggle('active',active);if(state)state.textContent=data?'Wert: '+data.value:'Nicht verfügbar'}
function renderValues(){const page=activePage();if(!page)return;page.items.filter(item=>item.type!=='label').forEach(item=>{const element=document.querySelector('.dashboard-item[data-id="'+cssEscape(item.id)+'"]');if(!element)return;if(item.type==='value')updateValueElement(element,item);else updateControlElement(element,item)})}
function cssEscape(value){return String(value).replace(/["\\]/g,'\\$&')}
function makeDraggable(element,item){let drag;element.addEventListener('pointerdown',event=>{if(event.button!==0||event.target.closest('button'))return;drag={x:event.clientX,y:event.clientY,left:item.x,top:item.y};element.setPointerCapture(event.pointerId);element.classList.add('dragging')});element.addEventListener('pointermove',event=>{if(!drag)return;item.x=Math.max(0,Math.round((drag.left+event.clientX-drag.x)/5)*5);item.y=Math.max(0,Math.round((drag.top+event.clientY-drag.y)/5)*5);element.style.left=item.x+'px';element.style.top=item.y+'px'});element.addEventListener('pointerup',()=>{if(!drag)return;drag=null;element.classList.remove('dragging');saveLayout()});if(item.type!=='pushbutton'&&item.type!=='switch')element.ondblclick=()=>editItem(item)}
function uniqueId(prefix){return prefix+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)}
function addPage(){const name=prompt('Name des neuen Reiters:','Neue Seite');if(!name?.trim())return;const page={id:uniqueId('page'),name:name.trim(),items:[]};layout.pages.push(page);activePageId=page.id;saveLayout()}
function renamePage(){const page=activePage();if(!page)return;const name=prompt('Name des Reiters:',page.name);if(!name?.trim())return;page.name=name.trim();saveLayout()}
function deletePage(){const page=activePage();if(!page||!confirm('Reiter „'+page.name+'“ löschen?'))return;if(layout.pages.length===1){toast('Mindestens ein Reiter muss vorhanden bleiben.',true);return}layout.pages=layout.pages.filter(candidate=>candidate.id!==page.id);activePageId=layout.pages[0].id;saveLayout()}
function addLabel(){const page=activePage();if(!page)return;const item={id:uniqueId('label'),type:'label',text:'Neues Label',x:20,y:20,width:220,height:70};page.items.push(item);render();editItem(item)}
function addValueField(){const page=activePage();if(!page)return;if(!catalog.length){toast('Es sind keine Datenkomponenten verfügbar.',true);return}const item={id:uniqueId('value'),type:'value',componentId:catalog[0].id,scale:1,unit:'',unitPlacement:'suffix',x:20,y:100,width:220,height:70};page.items.push(item);render();editItem(item)}
function addControl(type){const available=controlCatalog(type),page=activePage();if(!page)return;if(!available.length){toast('Es ist keine passende '+(type==='pushbutton'?'Pushbutton-':'Switch-')+'Datenquelle verfügbar.',true);return}const item={id:uniqueId(type),type,componentId:available[0].id,name:type==='pushbutton'?available[0].name:'',x:20,y:180,width:120,height:65};page.items.push(item);render();editItem(item)}
function controlCatalog(type){return catalog.filter(component=>component.webControl&&component.controlMode===type)}
function fillComponentSelect(select,components){select.replaceChildren();components.forEach(component=>select.add(new Option(component.name+' · '+component.datatype+' · ID '+component.id,component.id)))}
function editItem(item){if(!authState.canWrite)return;editingItemId=item.id;if(item.type==='label'){document.querySelector('#label-text').value=item.text;document.querySelector('#label-width').value=item.width;document.querySelector('#label-height').value=item.height||70;document.querySelector('#label-dialog').showModal()}else if(item.type==='value'){const select=document.querySelector('#value-component');fillComponentSelect(select,catalog);select.value=item.componentId;document.querySelector('#value-scale').value=item.scale??1;document.querySelector('#value-unit').value=item.unit||'';document.querySelector('#value-unit-placement').value=item.unitPlacement||'suffix';document.querySelector('#value-width').value=item.width;document.querySelector('#value-height').value=item.height||70;document.querySelector('#value-dialog').showModal()}else{const select=document.querySelector('#control-component'),name=document.querySelector('#control-name'),nameLabel=document.querySelector('#control-name-label');fillComponentSelect(select,controlCatalog(item.type));select.value=item.componentId;nameLabel.hidden=item.type!=='pushbutton';name.value=item.name||'';select.onchange=()=>{if(item.type==='pushbutton')name.value=controlCatalog(item.type).find(component=>String(component.id)===select.value)?.name||''};document.querySelector('#control-title').textContent=(item.type==='pushbutton'?'Pushbutton':'Switch')+' bearbeiten';document.querySelector('#control-width').value=item.width;document.querySelector('#control-height').value=item.height||65;document.querySelector('#control-dialog').showModal()}}
function findEditingItem(){return activePage()?.items.find(item=>item.id===editingItemId)}
function saveLabel(event){event.preventDefault();const item=findEditingItem();if(!item)return;item.text=document.querySelector('#label-text').value;item.width=Number(document.querySelector('#label-width').value);item.height=Number(document.querySelector('#label-height').value);document.querySelector('#label-dialog').close();saveLayout()}
function saveValueField(event){event.preventDefault();const item=findEditingItem(),scale=Number(document.querySelector('#value-scale').value);if(!item||!Number.isFinite(scale)){toast('Der Skalierungsfaktor ist ungültig.',true);return}item.componentId=Number(document.querySelector('#value-component').value);item.scale=scale;item.unit=document.querySelector('#value-unit').value;item.unitPlacement=document.querySelector('#value-unit-placement').value;item.width=Number(document.querySelector('#value-width').value);item.height=Number(document.querySelector('#value-height').value);document.querySelector('#value-dialog').close();saveLayout()}
function saveControl(event){event.preventDefault();const item=findEditingItem();if(!item)return;item.componentId=Number(document.querySelector('#control-component').value);if(item.type==='pushbutton')item.name=document.querySelector('#control-name').value.trim();item.width=Number(document.querySelector('#control-width').value);item.height=Number(document.querySelector('#control-height').value);document.querySelector('#control-dialog').close();saveLayout()}
function removeItem(id){if(!confirm('Element löschen?'))return;const page=activePage();page.items=page.items.filter(item=>item.id!==id);saveLayout()}
function saveLayout(){if(!authState.canWrite)return;render();send('dashboardSave:'+JSON.stringify(layout))}
function openAuthDialog(){const setup=authState.enabled&&!authState.initialized,dialog=document.querySelector('#auth-dialog');document.querySelector('#auth-title').textContent=setup?'Administrator anlegen':'Anmelden';document.querySelector('#auth-help').textContent=setup?'Legen Sie den ersten Administrator an.':'Melden Sie sich für den Zugriff auf das Dashboard an.';document.querySelector('#auth-submit').textContent=setup?'Administrator anlegen':'Anmelden';document.querySelector('#auth-confirm-label').hidden=!setup;document.querySelector('#auth-password-confirm').required=setup;if(!dialog.open)dialog.showModal()}
function submitAuthentication(event){event.preventDefault();const username=document.querySelector('#auth-username').value.trim(),password=document.querySelector('#auth-password').value,confirmPassword=document.querySelector('#auth-password-confirm').value;if(!authState.initialized&&password!==confirmPassword){toast('Die Passwörter stimmen nicht überein.',true);return}send((authState.initialized?'authLogin:':'authInitialize:')+JSON.stringify({username,password}));document.querySelector('#auth-password').value='';document.querySelector('#auth-password-confirm').value=''}
function logout(){send('authLogout');clearInterval(valueTimer)}
function toast(message,error=false){const element=document.querySelector('#toast');element.textContent=message;element.classList.toggle('error',error);element.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove('show'),3000)}
window.addEventListener('DOMContentLoaded',connect);
